#!/usr/bin/env bash
# Redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
path="/etc/nginx/sites-enabled/default"
sudo sed -i "/server_name _;\n\trewrite ^/(.*)$ redirect_me https://millonarios.com.co/ permanent;" "$path"
sudo service nginx start