#!/usr/bin/env bash
# Redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://millonarios.com.co/ permanent;/' /etc/nginx/sites-available/default
sudo service nginx start