#!/usr/bin/env bash
# Redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_error.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.millonarios.com.co permanent;" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /404_error.html;" /etc/nginx/sites-available/default
sudo service nginx start