#!/usr/bin/env bash
# Redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_error.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.millonarios.com.co permanent;\n\n\terror_page 404 \/404_error.html;\n\tlocation = \/404_error.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx start