#!/usr/bin/env bash
# script configure load balancer

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get install -y haproxy

CONF="\
listen http-in
	bind *:80
	mode http
	balance roundrobin
	server 1467-web-01 34.73.118.163:80 check
	server 1467-web-02 54.90.72.128:80 check
"

echo "$CONF" | sudo tee /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo service haproxy restart
