#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP status code from the Apache log file.
path="./apache-access.log"
awk -F' ' '{print $1, $9}' "$path" | sort -r | uniq -c | sort -r