#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, bad luck for the 4th loop iteration and good luck for the 8th loop iteration.
Holberton="Holberton School"
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then 
        echo "good luck"
    else
        echo "$Holberton"
    fi
    ((i++))
done
