#!/usr/bin/env bash
# script that gives you information about the holbertonschool file
if [ -e "holbertonschool" ]
then
    echo "holbertonschool file exists"
    if [ -s "holbertonschool" ]
    then
        echo "holbertonschool file is not empty"
        if [ -f "holbertonschool" ]
        then    
            echo "holbertonschool is a regular file"
        fi
    else
        echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
