#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$/'127.0.0.2 localhost'/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
